version: '3.8'

services:
  app:
    build:
      context: .
    image: app_service:latest
    ports:
      - "3000:8082"
    networks:
      - ai_network
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

networks:
  ai_network: